const data = {
  products: [
    {
      _id: '1',
      name: 'Beautiful Cups',
      category: 'Kitchen and Dining',
      image: '/images/cup.jpg',
      price: 25,
      countInStock: 10,
      brand: 'Designer Su',
      rating: 4.9,
      numReviews: 10,
      description: 'Nice cup with awesome design',
    },
    {
      _id: '2',
      name: 'Felix',
      category: 'digital',
      image: '/images/cutecat.jpg',
      price: 0.99,
      countInStock: 1,
      brand: 'Pet Lover',
      rating: 5.0,
      numReviews: 20,
      description: 'Cutest and Warmest Cat',
    },
    {
      _id: '3',
      name: 'Zooeum Cup',
      category: 'Kitchen and Dining',
      image: '/images/cup_Zooeum.jpg',
      price: 50.99,
      countInStock: 0,
      brand: 'Designer Su',
      rating: 4.8,
      numReviews: 17,
      description:
        'A very merry new 16oz Tritan can cup from Rudolph the Red-Nosed Reindeer!',
    },
    {
      _id: '4',
      name: 'Zooeum Bag',
      category: 'Bags',
      image: '/images/bag.jpeg',
      price: 78,
      countInStock: 15,
      brand: 'Designer Su',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Sleepy Cat',
      category: 'digital',
      image: '/images/sleepy_cat.jpg',
      price: 0.59,
      countInStock: 100,
      brand: 'Pet Lover',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality picture with a sleepy cat',
    },
    {
      _id: '6',
      name: 'Business Card',
      category: 'digital',
      image: '/images/card.jpg',
      price: 0.79,
      countInStock: 10000,
      brand: 'Designer Su',
      rating: 5.0,
      numReviews: 45,
      description: 'Most popular and beautiful design',
    },
  ],
}
export default data
